swagger: "2.0"
info: 
  version: "0.0.1"
  title: "boxstorage"
  description: "A service for box file storage using swagger-2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Box file storage REST Service"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/cloudmesh"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /put:
    post:
      tags:
        - BXS
      operationId: boxstor_openapi.put
      description: "Upload file to the specified directory"
      parameters:
        - in: body
          name: params 
          description: "Provide the directory name in body of the request"
          schema: 
            $ref: "#/definitions/PUT"
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "Upload file"
  /get:
    get:
      tags:
        - BXS
      operationId: boxstor_openapi.get
      description: "Download file from specified directory"
      parameters:
        - in: query
          name: service 
          description: "Provide the service name in body of the request"
          type: string
          required: true
        - in: query
          name: source 
          description: "Provide the source path in body of the request"
          type: string
          required: true
        - in: query
          name: destination 
          description: "Provide the destination path in body of the request"
          type: string
          required: true
        - in: query
          name: recursive 
          description: "Provide the recursive option in body of the request"
          type: string
          required: false
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "get files"
          schema: 
            $ref: "#/definitions/LIST"
  /list:
    get:
      tags:
        - BXS
      operationId: boxstor_openapi.list
      description: "Returns list of files and folders in the specified directory"
      parameters:
        - in: query
          name: service 
          description: "Provide the service name in body of the request"
          type: string
          required: true
        - in: query
          name: directory 
          description: "Provide the directory name in body of the request"
          type: string
          required: true
        - in: query
          name: recursive 
          description: "Provide the recursive option in body of the request"
          type: string
          required: false
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "list files"
          schema: 
            $ref: "#/definitions/LIST"
  /search:
    get:
      tags:
        - BXS
      operationId: boxstor_openapi.search
      description: "Searches the files in the specified directory"
      parameters:
        - in: query
          name: service 
          description: "Provide the service name in body of the request"
          type: string
          required: true
        - in: query
          name: directory 
          description: "Provide the directory name in body of the request"
          type: string
          required: true
        - in: query
          name: filename 
          description: "Provide the directory name in body of the request"
          type: string
          required: true
        - in: query
          name: recursive 
          description: "Provide the recursive option in body of the request"
          type: string
          required: false
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "search files"
          schema: 
            $ref: "#/definitions/LIST"
  /delete:
    get:
      tags:
        - BXS
      operationId: bxstor_openapi.delete
      description: "Deletes the files in the specified directory"
      parameters:
        - in: query
          name: service 
          description: "Provide the service name in body of the request"
          type: string
          required: true
        - in: query
          name: source 
          description: "Provide the source name in body of the request"
          type: string
          required: true
        - in: query
          name: recursive 
          description: "Provide the recursive option in body of the request"
          type: string
          required: false
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "delete files"
          schema: 
            $ref: "#/definitions/LIST"
  /create_dir:
    get:
      tags:
        - BXS
      operationId: azstor_openapi.create_dir
      description: "creates the specified directory"
      parameters:
        - in: query
          name: service 
          description: "Provide the service name in body of the request"
          type: string
          required: true
        - in: query
          name: directory 
          description: "Provide the directory name in body of the request"
          type: string
          required: true
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "create directory"
          schema: 
            $ref: "#/definitions/LIST"

definitions:
  PUT:
    type: "object"
    required: 
      - "service"
      - "source"
      - "destination"
      - "recursive"
    properties: 
      service:
        type: "string"
      source:
        type: "string"
      destination:
        type: "string"
      recursive:
        type: "string"
  LIST:
    type: "object"
    required: 
      - "d"
    properties: 
      d:
        type: "string"
